### ISSUE TITLE
Error when running p2pool

### ISSUE THREAD

**Issue by Tanariel** [Groestlcoin/p2pool-grs#6]
I'm getting this error when running p2pool.

```
Error getting work from bitcoind:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/root/p2pool-grs/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/p2pool-grs/p2pool/bitcoin/helper.py", line 36, in getwork
    work = yield go()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/p2pool-grs/p2pool/util/jsonrpc.py", line 143, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: -8 Support for 'segwit' rule requires explicit client support
```

I am not exactly sure what i should change for that to run.
The wallet is running and is synced. I guess there is a segwit parameter or configuration that needs to be done somewhere ?

**Comment by gruve-p** [comment]
What version of Groestlcoin Core are you running?
Can you try this: https://github.com/Groestlcoin/p2pool-grs-setupguide

**Comment by Tanariel** [comment]
I followed somehow this guide yes, the wallet version is :  Groestlcoin version v2.13.3

**Comment by foxy6624** [comment]
the same issue with Groestlcoin core version v2.13.3. Maybe it's the problem of p2pool-grs for there is no maintenance for a long time...
https://github.com/Groestlcoin/p2pool-grs/blob/master/p2pool/data.py
and 
https://github.com/p2pool/p2pool/blob/master/p2pool/data.py

are not the same

**Comment by gruve-p** [comment]
Our p2pool code is very outdated indeed.

**Comment by Tanariel** [comment]
I would be very happy to help out the community by setupping some node, but for the code i can’t help :(

**Comment by gruve-p** [comment]
Is this issue resolved? Can you confirm?

**Comment by Tanariel** [comment]
I can confirm. :)

**Comment by gruve-p** [comment]
This repo has been deprecated.
New repo: https://github.com/Groestlcoin/p2pool/
